# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-19 17:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeActions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_date', models.DateField()),
                ('operation_time', models.TimeField()),
                ('person_action', models.CharField(max_length=200)),
                ('money_balance', models.CharField(max_length=200)),
                ('action_comment', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='OrdinaryCashier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinary_cashier_name', models.CharField(blank=True, max_length=20, unique=True)),
                ('cashier_description_full', models.CharField(blank=True, max_length=600)),
                ('cashier_description_short', models.CharField(blank=True, max_length=100)),
                ('exchange_rate', models.CharField(blank=True, max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='exchangeactions',
            name='person_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ExchangeHelper.OrdinaryCashier'),
        ),
    ]
