# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-22 10:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ExchangeHelper', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exchangeactions',
            old_name='action_comment',
            new_name='action',
        ),
        migrations.RemoveField(
            model_name='exchangeactions',
            name='person_action',
        ),
    ]
