# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-24 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExchangeHelper', '0002_auto_20170422_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordinarycashier',
            name='ordinary_cashier_name',
        ),
        migrations.AddField(
            model_name='exchangeactions',
            name='person_surname',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
