# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-14 14:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ExchangeHelper', '0003_auto_20170514_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchangeactions',
            name='action',
        ),
    ]
