# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-24 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExchangeHelper', '0003_auto_20170424_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangeactions',
            name='person_surname',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='ordinarycashier',
            name='cashier_description_full',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='ordinarycashier',
            name='cashier_description_short',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ordinarycashier',
            name='exchange_rate',
            field=models.CharField(max_length=200),
        ),
    ]
