# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-24 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExchangeHelper', '0004_auto_20170424_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordinarycashier',
            name='exchange_rate',
            field=models.CharField(max_length=400),
        ),
    ]
