# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-15 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExchangeHelper', '0004_remove_exchangeactions_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangeactions',
            name='operation_activity',
            field=models.BooleanField(default=False),
        ),
    ]
