# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-15 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExchangeHelper', '0006_auto_20170515_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangeactions',
            name='currency_changes',
            field=models.CharField(max_length=100),
        ),
    ]
