# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-15 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExchangeHelper', '0007_auto_20170515_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangeactions',
            name='possibility_of_operation',
            field=models.BooleanField(default=True),
        ),
    ]
