# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-30 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExchangeHelper', '0008_auto_20170516_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangeactions',
            name='operation_profit',
            field=models.FloatField(default=0),
        ),
    ]
