# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-30 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExchangeHelper', '0009_exchangeactions_operation_profit'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangeactions',
            name='increase_exchange_rate',
            field=models.FloatField(default=0),
        ),
    ]
