# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-31 23:01
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExchangeHelper', '0010_exchangeactions_increase_exchange_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncreaseOperations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_date', models.DateField()),
                ('operation_time', models.TimeField()),
                ('person_surname', models.CharField(max_length=20)),
                ('action_type', models.CharField(max_length=20)),
                ('increase_exchange_rate', models.FloatField(default=0)),
                ('increase_currency', models.CharField(max_length=5)),
                ('increase_summ', models.FloatField()),
                ('comment', models.CharField(max_length=200)),
                ('possibility_of_operation', models.BooleanField(default=True)),
                ('person_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ExchangeHelper.OrdinaryCashier')),
            ],
        ),
        migrations.RemoveField(
            model_name='exchangeactions',
            name='increase_exchange_rate',
        ),
    ]
