# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-31 23:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ExchangeHelper', '0011_auto_20170601_0201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='increaseoperations',
            name='action_type',
        ),
    ]
