# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-01 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExchangeHelper', '0012_remove_increaseoperations_action_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangeactions',
            name='used_increases',
            field=models.CharField(default='', max_length=200),
        ),
    ]
