# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-05 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExchangeHelper', '0013_exchangeactions_used_increases'),
    ]

    operations = [
        migrations.AddField(
            model_name='increaseoperations',
            name='increase_operation_id',
            field=models.IntegerField(default=0),
        ),
    ]
