# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-05 21:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ExchangeHelper', '0015_increaseoperations_usability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='increaseoperations',
            name='possibility_of_operation',
        ),
    ]
