# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-05 21:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ExchangeHelper', '0016_remove_increaseoperations_possibility_of_operation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='increaseoperations',
            name='comment',
        ),
    ]
