# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-07 10:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ExchangeHelper', '0017_remove_increaseoperations_comment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdministratorCashCosts',
            new_name='AdministratorScraps',
        ),
    ]
