# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-06-11 23:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ExchangeHelper', '0018_auto_20170607_1340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchangeactions',
            name='used_increases',
        ),
    ]
